spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/lab4
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: false
    locations: classpath:db/migrations

server:
  port: 8080

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html